/**
 * Parity with the Python engine (ADR-0005).
 *
 * Vectors are generated by `make fixtures` and never hand-edited. A failure here
 * means the two implementations disagree — fix the mirror, don't edit the data.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { helpAction, type HelpAction } from '../src/help.js';
import { needsPrerequisiteProbe, nextLevel, startingLevel } from '../src/ladder.js';
import {
  band,
  chanceLevelForOptions,
  confidence,
  displayedMastery,
  retainedMastery,
  update,
  type Attempt,
  type SkillRating,
} from '../src/mastery.js';
import { ENGINE_VERSION } from '../src/version.js';

interface Case {
  id: string;
  kind: string;
  input: Record<string, unknown>;
  expected: Record<string, unknown>;
}

interface Vectors {
  engine_version: string;
  tolerance: number;
  cases: Case[];
}

const here = dirname(fileURLToPath(import.meta.url));
const vectorsPath = resolve(here, '../../fixtures/vectors.json');
const vectors = JSON.parse(readFileSync(vectorsPath, 'utf8')) as Vectors;

describe('engine parity', () => {
  it('mirrors the Python engine version', () => {
    expect(ENGINE_VERSION).toBe(vectors.engine_version);
  });

  it('has cases to check', () => {
    expect(vectors.cases.length).toBeGreaterThan(0);
  });

  for (const testCase of vectors.cases) {
    it(testCase.id, () => {
      const { input, expected } = testCase;
      const near = (actual: number, want: number) =>
        expect(Math.abs(actual - want)).toBeLessThanOrEqual(vectors.tolerance);

      switch (testCase.kind) {
        case 'mastery.update': {
          const result = update(input.rating as SkillRating, input.attempt as Attempt);
          const want = expected.rating as SkillRating;
          near(result.theta, want.theta);
          expect(result.scored_attempts).toBe(want.scored_attempts);
          expect(result.levels_seen).toEqual(want.levels_seen);
          near(displayedMastery(result), expected.displayed_mastery as number);
          expect(band(result)).toBe(expected.band);
          expect(confidence(result)).toBe(expected.confidence);
          break;
        }
        case 'mastery.retained': {
          near(
            retainedMastery(
              input.mastery as number,
              input.days_since_success as number,
              input.half_life_days as number,
              input.chance_level as number,
            ),
            expected.retained_mastery as number,
          );
          break;
        }
        case 'mastery.chance_level': {
          near(
            chanceLevelForOptions(input.option_count as number),
            expected.chance_level as number,
          );
          break;
        }
        case 'ladder.next_level': {
          const level = input.current_level as number;
          const outcomes = input.recent_outcomes as boolean[];
          expect(nextLevel(level, outcomes)).toBe(expected.next_level);
          expect(needsPrerequisiteProbe(level, outcomes)).toBe(expected.needs_prerequisite_probe);
          break;
        }
        case 'ladder.starting_level': {
          expect(startingLevel(input.rating as SkillRating)).toBe(expected.starting_level);
          break;
        }
        case 'help.action': {
          const action = helpAction({
            mastery: input.mastery as number,
            wrong_in_session: input.wrong_in_session as number,
            hint_shown: input.hint_shown as boolean,
          });
          expect(action).toBe(expected.action as HelpAction);
          break;
        }
        default:
          throw new Error(`unknown case kind: ${testCase.kind}`);
      }
    });
  }
});
